name: Generate ISO image

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  geniso:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64, riscv64]
        include:
          - arch: x86_64
            debarch: amd64
          - arch: aarch64
            debarch: arm64
          - arch: riscv64
            debarch: riscv64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.arch }}
      - name: Upgrade ubuntu
        run: |
          sudo sed -i 's/jammy/mantic/' /etc/apt/sources.list
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget dosfstools arch-install-scripts sudo pacman-package-manager xorriso arch-install-scripts squashfs-tools systemd-container
      - name: Setup pacman config to europe repo
        run: |
          wget https://raw.githubusercontent.com/eweOS/packages/pacman/pacman.conf -O pacman.ewe.conf
          sed -i 's/os-repo.ewe.moe/os-repo-bak.ewe.moe/' pacman.ewe.conf
      - name: Build ISO for ${{ matrix.arch }}
        run: |
          ./gen.sh liveimage-minimal ${{ matrix.arch }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: eweos-${{ matrix.arch }}
          path: results
          compression-level: 0
