name: Generate ISO image

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  geniso:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64, riscv64]
        variant: [liveimage-desktop, liveimage-minimal, tarball]
        include:
          - arch: x86_64
            debarch: amd64
          - arch: aarch64
            debarch: arm64
          - arch: riscv64
            debarch: riscv64
    runs-on: ubuntu-latest
    name: Generate ISO for ${{ matrix.variant }} - ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.arch }}
      - name: Upgrade ubuntu
        run: |
          sudo sed -i 's/jammy/mantic/' /etc/apt/sources.list
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget dosfstools arch-install-scripts sudo pacman-package-manager xorriso arch-install-scripts squashfs-tools systemd-container
      - name: Setup pacman config to europe repo
        run: |
          wget https://raw.githubusercontent.com/eweOS/packages/pacman/pacman.conf -O pacman.ewe.conf
          sed -i 's/os-repo.ewe.moe/os-repo-bak.ewe.moe/' pacman.ewe.conf
      - name: Build ISO for ${{ matrix.variant }} - ${{ matrix.arch }}
        run: |
          ./gen.sh ${{ matrix.variant }} ${{ matrix.arch }}
      - name: Check build Results
        id: buildresult
        run: |
          ls results/ | grep -v .sha256
          ls results/ | grep .sha256
          echo "ART_FILE=$(ls results/ | grep -v .sha256 | head -n 1)" >> $GITHUB_OUTPUT
          echo "ART_SUM=$(ls results/ | grep .sha256 | head -n 1)" >> $GITHUB_OUTPUT
      - name: Upload artifact (file)
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.buildresult.outputs.ART_FILE}}
          path: results/${{steps.build.outputs.ART_FILE}}
          compression-level: 0
      - name: Upload artifact (checksum)
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.buildresult.outputs.ART_SUM}}
          path: results/${{steps.build.outputs.ART_SUM}}
          compression-level: 0
